import { tokens } from './tokens.js';

/**
 * Build-time codegen failures. Distinct from runtime DomainError types
 * (`@dankdash/types`) because this code never runs at request time — it's
 * a pnpm build step that produces Swift source. Subclassing Error keeps
 * `@typescript-eslint/only-throw-error` happy without pulling a runtime
 * dependency into the design-tokens package.
 */
export class TokenCodegenError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'TokenCodegenError';
  }
}

/**
 * Pure Swift source emitter. Returns the generated file body verbatim;
 * the caller writes it to disk. Kept side-effect-free so we can snapshot
 * the output in unit tests and gate drift in CI.
 */
export function emitSwift(): string {
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by @dankdash/design-tokens. Do not edit by hand.');
  lines.push('// Source: packages/design-tokens/src/tokens.ts');
  lines.push('// Regenerate: pnpm --filter @dankdash/design-tokens build');
  lines.push('');
  lines.push('import SwiftUI');
  lines.push('');
  lines.push('/// Internal token constants generated from the @dankdash/design-tokens');
  lines.push('/// vocabulary. Public `DankColor`, `DankSpacing`, `DankRadius`, and');
  lines.push('/// `DankFont` enums alias these — call sites should keep using the');
  lines.push('/// public surface, not reach into `GeneratedTokens` directly.');
  lines.push('internal enum GeneratedTokens {');

  lines.push('  internal enum Palette {');
  for (const [step, hex] of Object.entries(tokens.color.primary)) {
    lines.push(`    internal static let primary${step} = ${swiftColorFromHex(hex)}`);
  }
  lines.push(`    internal static let background = ${swiftColorFromHex(tokens.color.background)}`);
  lines.push(`    internal static let glass = ${swiftColorFromCss(tokens.color.glass)}`);
  for (const [name, hex] of Object.entries(tokens.color.semantic)) {
    lines.push(`    internal static let semantic${capitalize(name)} = ${swiftColorFromHex(hex)}`);
  }
  for (const [name, hex] of Object.entries(tokens.color.status)) {
    lines.push(`    internal static let status${capitalize(name)} = ${swiftColorFromHex(hex)}`);
  }
  for (const [name, hex] of Object.entries(tokens.color.text)) {
    lines.push(`    internal static let text${capitalize(name)} = ${swiftColorFromHex(hex)}`);
  }
  lines.push('  }');
  lines.push('');

  lines.push('  internal enum Spacing {');
  for (const [name, value] of Object.entries(tokens.spacing)) {
    lines.push(`    internal static let ${name}: CGFloat = ${value}`);
  }
  lines.push('  }');
  lines.push('');

  lines.push('  internal enum Radius {');
  for (const [name, value] of Object.entries(tokens.radius)) {
    lines.push(`    internal static let ${name}: CGFloat = ${value}`);
  }
  lines.push('  }');
  lines.push('');

  lines.push('  internal enum Typography {');
  for (const [name, spec] of Object.entries(tokens.typography)) {
    const textStyle = swiftTextStyleForSize(spec.size);
    const design = swiftFontDesign(spec.design);
    const weight = swiftFontWeight(spec.weight);
    lines.push(
      `    internal static let ${name}: Font = .system(${textStyle}, design: ${design}, weight: ${weight})`,
    );
    lines.push(`    internal static let ${name}Size: CGFloat = ${spec.size}`);
  }
  lines.push('  }');
  lines.push('');

  lines.push('  internal enum Shadow {');
  for (const [name, spec] of Object.entries(tokens.shadow)) {
    lines.push(`    internal enum ${capitalize(name)} {`);
    lines.push(`      internal static let color = ${swiftColorFromCss(spec.ios.color)}`);
    lines.push(`      internal static let radius: CGFloat = ${spec.ios.radius}`);
    lines.push(`      internal static let x: CGFloat = ${spec.ios.x}`);
    lines.push(`      internal static let y: CGFloat = ${spec.ios.y}`);
    lines.push(`    }`);
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function swiftColorFromHex(hex: string): string {
  const { r, g, b, a } = parseColor(hex);
  return swiftColorLiteral(r, g, b, a);
}

function swiftColorFromCss(css: string): string {
  const { r, g, b, a } = parseColor(css);
  return swiftColorLiteral(r, g, b, a);
}

function swiftColorLiteral(r: number, g: number, b: number, a: number): string {
  return `Color(.sRGB, red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)}, opacity: ${fmt(a)})`;
}

interface RGBA {
  r: number;
  g: number;
  b: number;
  a: number;
}

function parseColor(input: string): RGBA {
  const trimmed = input.trim();
  if (trimmed.startsWith('#')) {
    return parseHex(trimmed.slice(1));
  }
  const rgbaMatch =
    /^rgba?\(\s*([0-9.]+)\s*,\s*([0-9.]+)\s*,\s*([0-9.]+)\s*(?:,\s*([0-9.]+)\s*)?\)$/i.exec(
      trimmed,
    );
  if (rgbaMatch) {
    const [, rs, gs, bs, as] = rgbaMatch;
    return {
      r: Number(rs) / 255,
      g: Number(gs) / 255,
      b: Number(bs) / 255,
      a: as === undefined ? 1 : Number(as),
    };
  }
  throw new TokenCodegenError(`Unrecognized color literal: ${input}`);
}

function parseHex(hex: string): RGBA {
  if (hex.length !== 6 && hex.length !== 8) {
    throw new TokenCodegenError(`Invalid hex color: #${hex}`);
  }
  const r = parseInt(hex.slice(0, 2), 16) / 255;
  const g = parseInt(hex.slice(2, 4), 16) / 255;
  const b = parseInt(hex.slice(4, 6), 16) / 255;
  const a = hex.length === 8 ? parseInt(hex.slice(6, 8), 16) / 255 : 1;
  return { r, g, b, a };
}

function fmt(value: number): string {
  return Number(value.toFixed(4)).toString();
}

function swiftTextStyleForSize(size: number): string {
  // Mapping mirrors Apple's documented default point sizes at
  // `.large` Dynamic Type. Values picked to match the existing
  // DankFont surface exactly.
  if (size >= 34) return '.largeTitle';
  if (size >= 28) return '.title';
  if (size >= 22) return '.title2';
  if (size >= 20) return '.title3';
  if (size >= 17) return '.body';
  if (size >= 15) return '.subheadline';
  if (size >= 13) return '.footnote';
  return '.caption';
}

function swiftFontDesign(design: string): string {
  switch (design) {
    case 'rounded':
      return '.rounded';
    case 'monospaced':
      return '.monospaced';
    case 'serif':
      return '.serif';
    default:
      return '.default';
  }
}

function swiftFontWeight(weight: string): string {
  switch (weight) {
    case 'thin':
    case 'light':
    case 'ultraLight':
    case 'regular':
    case 'medium':
    case 'semibold':
    case 'bold':
    case 'heavy':
    case 'black':
      return `.${weight}`;
    default:
      throw new TokenCodegenError(`Unknown font weight: ${weight}`);
  }
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
