export {
  DomainError,
  ValidationError,
  AuthError,
  ForbiddenError,
  NotFoundError,
  ConflictError,
  ComplianceError,
  InventoryError,
  PaymentError,
  ExternalServiceError,
  RateLimitError,
  RepositoryError,
  EncryptionError,
  type EncryptionErrorCode,
  ConfigError,
  type ConfigErrorCode,
  PasswordError,
  type PasswordErrorCode,
  type ErrorDetails,
  type ErrorEnvelope,
  toErrorEnvelope,
} from './errors.js';
