// @ts-check
/**
 * Portal ESLint config.
 *
 * The portal is the only Next.js app in the monorepo today, so it owns its
 * own flat config rather than threading Next-specific rules through
 * @dankdash/config (which is consumed by Node/NestJS packages that don't
 * need React/Next plugins).
 *
 * We do extend the shared config so the workspace-wide rules (no-console,
 * type-aware safety, import order, no-explicit-any) still apply, plus the
 * shared test-file relaxations; the per-package additions below stack on
 * top.
 */
import sharedConfig from '../../packages/config/eslint.config.js';

export default [
  ...sharedConfig,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // React Server Component files are server-only; client components are
      // tagged with `'use client'`. We rely on Next's compiler to enforce
      // that boundary; the lint config does not need to.
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },
  {
    files: [
      'next.config.mjs',
      'postcss.config.mjs',
      'tailwind.config.ts',
      'vitest.config.ts',
      'vitest.setup.ts',
      'playwright.config.ts',
    ],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  // Generated by Next during `next build`. Not worth linting.
  {
    ignores: [
      '.next/**',
      'next-env.d.ts',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },
];
