// @ts-check
/**
 * Portal ESLint config.
 *
 * The portal is the only Next.js app in the monorepo today, so it owns its
 * own flat config rather than threading Next-specific rules through
 * @dankdash/config (which is consumed by Node/NestJS packages that don't
 * need React/Next plugins).
 *
 * We do extend the shared config so the workspace-wide rules (no-console,
 * type-aware safety, import order, no-explicit-any) still apply; the per-
 * package additions below stack on top.
 *
 * Test files relax `no-floating-promises` and the strict unsafe rules —
 * RTL's user-event API returns promises that consumers usually await but
 * may legitimately fire-and-forget in setup helpers; the test layer
 * already runs in a sandboxed jsdom and the strict rules add noise
 * without catching real bugs.
 */
import sharedConfig from '../../packages/config/eslint.config.js';

export default [
  ...sharedConfig,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      // React Server Component files are server-only; client components are
      // tagged with `'use client'`. We rely on Next's compiler to enforce
      // that boundary; the lint config does not need to.
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },
  {
    files: [
      'next.config.mjs',
      'postcss.config.mjs',
      'tailwind.config.ts',
      'vitest.config.ts',
      'vitest.setup.ts',
      'playwright.config.ts',
    ],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  {
    files: ['test/**/*.{ts,tsx}', '**/*.test.{ts,tsx}'],
    rules: {
      // Test helpers fire promises and bind methods freely; production
      // rules around those patterns add noise without catching real
      // bugs inside a sandboxed jsdom + vitest harness.
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/unbound-method': 'off',
      // `vi.fn(async (req) => new Response(...))` mock implementations
      // exist to match `fetch`'s `Promise<Response>` contract — the
      // body legitimately has no await. Same for one-line mock factories
      // that wrap a sync return.
      '@typescript-eslint/require-await': 'off',
      // vitest spies are typed `any`; relaxing return + base-to-string
      // here lets test mocks read naturally.
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      // Generic `void` and void-expression patterns show up in test
      // helpers (typed request<void>(), one-line arrow wrappers).
      '@typescript-eslint/no-invalid-void-type': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      // Tests deliberately assert on values across guards and `as`-cast
      // through opaque internals to exercise narrow code paths.
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      // `throw new Error("test scaffolding precondition")` is allowed
      // in test helpers — these never reach production and the typed
      // DomainError pattern only applies to real domain code.
      'no-restricted-syntax': 'off',
      // Type-only imports in tests are commonly grouped beside their
      // value-import companions for legibility.
      'import/order': 'off',
    },
  },
  // Generated by Next during `next build`. Not worth linting.
  {
    ignores: [
      '.next/**',
      'next-env.d.ts',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },
];
